backend:
  name: git-gateway
  branch: main
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "profile-picture"
    label: "Profile Picture"
    folder: "pages/index"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}

   - name: "articles"
    label: "Articles"
    folder: "pages/index"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Text", name: "text", widget: "text"}

  - name: "photos"
    label: "Photos"
    folder: "pages/galerie"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}

  - name: "cards"
    label: "Cards"
    folder: "pages/tarifs"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
       - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "number"}



